### CADASTRO

POST http://localhost:3003/users/signup
Content-Type: application/json

{
	"name": "Bruno Vallim",
	"nickname":"bvallim",
	"email": "bruno@gmail.com",
	"password": "123456"

}

### LOGIN
# @name login
POST http://localhost:3003/users/login
Content-Type: application/json

{
	"email": "bruno@gmail.com",
	"password": "123456"
}

###
@token = {{login.response.body.accessToken}}
POST http://localhost:3003/music/create
Content-Type: application/json
Authorization: {{token}}

{
	"band":"Foo Fighters",
	"music":"Run",
	"music_genre":"Rock",
	"url": "https://www.youtube.com/watch?v=ifwc5xgI3QM&ab_channel=foofightersVEVO"
	
}

###
GET http://localhost:3003/music/getAll/069eeb1f-7e7d-483d-8fe3-c972ce3713b2
Content-Type: application/json
Authorization: {{token}}

###
@token = {{login.response.body.accessToken}}
POST http://localhost:3003/playlist/createPlaylist
Content-Type: application/json
Authorization: {{token}}

{
	"name": "Rock da Pesada"
	
}

###
GET http://localhost:3003/playlist/getAll/8eb30772-3b5b-448f-a7fc-073b46b253f4
Content-Type: application/json
Authorization: {{token}}